<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
    <PackageReference Include="FluentAssertions" Version="6.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.2" />
    <PackageReference Include="SpecFlow" Version="3.9.74" />
    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.74" PrivateAssets="all" />
    <PackageReference Include="SpecFlow.NUnit" Version="3.9.74" />
    <PackageReference Include="NUnit" Version="3.13.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Burn_Out.Client\Burn_Out.Client.csproj" />
    <ProjectReference Include="..\Burn_Out.FunctionalTests\Burn_Out.FunctionalTests.csproj" />
    <ProjectReference Include="..\Burn_Out.UnitTests\Burn_Out.UnitTests.csproj" />
    <ProjectReference Include="..\Burn_Out\Burn_Out.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Features\Login.feature">
      <Generator>SpecFlowSingleFileGenerator</Generator>
      <LastGenOutput>Login.feature.cs</LastGenOutput>
    </None>
    <None Update="Features\HallReservation.feature">
      <Generator>SpecFlowSingleFileGenerator</Generator>
      <LastGenOutput>HallReservation.feature.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
