<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SpecFlow" Version="4.0.31-beta" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Burn_Out.UnitTests\Burn_Out.UnitTests.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Burn_Out.AcceptanceTest.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.1" />
  </ItemGroup>

</Project>